---
- name: Install Fedora-specific libraries and programs
  dnf:
    name: "{{ item }}"
  with_items:
    - freetype-freeworld
    - gstreamer-ffmpeg
    - gstreamer-plugins-bad
    - gstreamer-plugins-ugly
    - flash-plugin
    - messengerfordesktop
    - steam
    - xine-lib-extras-freeworld
  become: true

# TODO: Install Nylas Mail from https://edgehill.nylas.com/download?platform=linux-rpm

- name: Install opam for OCaml
  shell: wget https://raw.github.com/ocaml/opam/master/shell/opam_installer.sh -O - | sh -s /usr/local/bin
  become: true
