---
- name: Download some RPM's
  get_url:
    url: "{{ item.url }}"
    dest: "/tmp/{{ item.name }}.rpm"
  with_items:
    - url: https://go.microsoft.com/fwlink/?LinkID=760867
      name: visual-studio-code

- name: Install Fedora-specific libraries and programs
  dnf:
    name: "{{ item }}"
  with_items:
    - freetype-freeworld
    - gstreamer-ffmpeg
    - gstreamer-plugins-bad
    - gstreamer-plugins-ugly
    - flash-plugin
    - messengerfordesktop
    - steam
    - xine-lib-extras-freeworld
    - /tmp/visual-studio-code.rpm
  become: true

- name: Install opam for OCaml
  shell: wget https://raw.github.com/ocaml/opam/master/shell/opam_installer.sh -O - | sh -s /usr/local/bin
  become: true
