---
- name: Download Nylas mail
  get_url:
    url: https://edgehill.nylas.com/download?platform=linux-rpm
    dest: /tmp/nylas-mail.rpm

- name: Install Fedora-specific libraries and programs
  dnf:
    name: "{{ item }}"
  with_items:
    - freetype-freeworld
    - gstreamer-ffmpeg
    - gstreamer-plugins-bad
    - gstreamer-plugins-ugly
    - flash-plugin
    - messengerfordesktop
    - steam
    - xine-lib-extras-freeworld
    - /tmp/nylas-mail.rpm
  become: true

- name: Install opam for OCaml
  shell: wget https://raw.github.com/ocaml/opam/master/shell/opam_installer.sh -O - | sh -s /usr/local/bin
  become: true
