---
- name: Setup Visual Studio Code's RPM Repo
  yum_repository:
    name: vscode
    description: Visual Studio Code
    baseurl: https://packages.microsoft.com/yumrepos/vscode
    enabled: yes
    gpgcheck: yes
    gpgkey: https://packages.microsoft.com/keys/microsoft.asc
  become: true

- name: Get Google's GPG Key
  rpm_key:
    key: http://dl-ssl.google.com/linux/linux_signing_key.pub
  become: true

- name: Setup Google Chrome's RPM Repo
  yum_repository:
    name: google-chrome
    description: Google Chrome
    baseurl: http://dl.google.com/linux/chrome/rpm/stable/x86_64
    enabled: yes
    gpgcheck: yes
    gpgkey: http://dl-ssl.google.com/linux/linux_signing_key.pub
  become: true

- name: Install Fedora-specific libraries and programs
  dnf:
    name: "{{ item }}"
    state: latest
  with_items:
    - code # visual studio code
    - freetype-freeworld
    - golang
    - google-chrome-stable
    - gstreamer-ffmpeg
    - gstreamer-plugins-bad
    - gstreamer-plugins-ugly
    - flash-plugin
    - python-devel
    - messengerfordesktop
    - redhat-rpm-config
    - https://downloads.slack-edge.com/linux_releases/slack-2.8.2-0.1.fc21.x86_64.rpm
    - steam
    - xine-lib-extras-freeworld
  become: true

- name: Install opam for OCaml
  shell: wget https://raw.github.com/ocaml/opam/master/shell/opam_installer.sh -O - | sh -s /usr/local/bin
  become: true
