---
- name: Install Fedora-specific libraries and programs
  dnf:
    name: "{{ item }}"
  with_items:
    - freetype-freeworld
    - gstreamer-ffmpeg
    - gstreamer-plugins-bad
    - gstreamer-plugins-ugly
    - flash-plugin
    - messengerfordesktop
    - steam
    - thunderbird
    - xine-lib-extras-freeworld
    - yakyak
  become: true
