---
- name: Get Microsoft's GPG Key
  rpm_key:
    key: https://packages.microsoft.com/keys/microsoft.asc
  become: true

- name: Setup Visual Studio Code's RPM Repo
  yum_repository:
    name: vscode
    description: Visual Studio Code
    baseurl: https://packages.microsoft.com/yumrepos/vscode
    enabled: yes
    gpgcheck: yes
    gpgkey: https://packages.microsoft.com/keys/microsoft.asc
  become: true

- name: Install Fedora-specific libraries and programs
  dnf:
    name: "{{ item }}"
    state: latest
  with_items:
    - code # visual studio code
    - freetype-freeworld
    - gstreamer-ffmpeg
    - gstreamer-plugins-bad
    - gstreamer-plugins-ugly
    - flash-plugin
    - python-devel
    - messengerfordesktop
    - redhat-rpm-config
    - steam
    - xine-lib-extras-freeworld
  become: true

- name: Install opam for OCaml
  shell: wget https://raw.github.com/ocaml/opam/master/shell/opam_installer.sh -O - | sh -s /usr/local/bin
  become: true
