---
- import_tasks: fedora.yml
  when: ansible_distribution == "Fedora"

- import_tasks: ubuntu.yml
  when: ansible_distribution == "Ubuntu"

- name: Install Linux-specific packages
  package: name={{ item }}
  with_items:
    - geary
  become: true

- name: Fix antialiasing
  gsetting:
    schema: "{{ item.schema }}"
    key: "{{ item.key }}"
    value: "{{ item.value }}"
  with_items:
    - schema: org.gnome.settings-daemon.plugins.xsettings
      key: hinting
      value: "'slight'"
    - schema: org.gnome.settings-daemon.plugins.xsettings
      key: antialiasing
      value: "'rgba'"

- name: Fix PulseAudio flat volumes
  ini_file:
    dest: /etc/pulse/daemon.conf
    create: no
    section: null
    option: flat-volumes
    value: 'no'
  become: true
  notify:
  - restart pulseaudio

- name: Create VS Code settings folder
  file:
    dest: "{{ '~/.config/Code/User' | expanduser }}"
    state: directory

- name: Set Visual Studio Code settings
  copy:
    src: files/vs-code.json
    dest: "{{ '~/.config/Code/User/settings.json' | expanduser }}"
