---
- include: fedora.yml
  when: ansible_distribution == "Fedora"

- include: ubuntu.yml
  when: ansible_distribution == "Ubuntu"

- name: Download Nylas mail
  get_url:
    url: https://edgehill.nylas.com/download?platform=linux-rpm
    dest: /tmp/nylas-mail.rpm

- name: Install Linux-specific packages
  package: name={{ item }}
  with_items:
    - atom
    - firefox
    - /tmp/nylas-mail.rpm
  become: true

- name: Fix antialiasing
  gsetting:
    schema: "{{ item.schema }}"
    key: "{{ item.key }}"
    value: "{{ item.value }}"
  with_items:
    - schema: org.gnome.settings-daemon.plugins.xsettings
      key: hinting
      value: "'slight'"
    - schema: org.gnome.settings-daemon.plugins.xsettings
      key: antialiasing
      value: "'rgba'"

- name: Fix PulseAudio flat volumes
  ini_file:
    dest: /etc/pulse/daemon.conf
    create: no
    section: null
    option: flat-volumes
    value: 'no'
  become: true
  notify:
  - restart pulseaudio
