---
- name: Install Mac specific programs
  homebrew_cask: name={{ item }}
  with_items:
    - battle-net
    - cyberduck
    - docker
    - firefox
    - gimp
    - gitter
    - google-chrome
    - hyperswitch
    - iterm2
    - java
    - messenger-for-desktop
    - nylas-mail
    - slack
    - spectacle
    - sqlpro-for-mssql
    - steermouse
    - swinsian
    # missing: Todoist
    - tunnelblick
    - virtualbox
    - visual-studio-code
    - wireshark
    - yakyak

- name: Install 'brew cu' for upgrading casks
  homebrew_tap:
    name: buo/cask-upgrade

- name: Install Mac specific CLI apps
  homebrew: name={{ item }}
  with_items:
    - opam

- name: Setup 'brew update' cron job
  cron:
    name: Update Homebrew package list
    job: brew update
    special_time: daily

- name: Setup Homebrew cask upgrade cron job
  cron:
    name: Update Homebrew casks
    job: brew cu -a --cleanup -y
    special_time: daily

- name: Setup 'brew upgrade' cron job
  cron:
    name: Upgrade Homebrew packages
    job: brew upgrade -y
    special_time: daily
