---
- include: fedora.yml
  when: ansible_distribution == "Fedora"

- include: linux.yml
  when: ansible_os_family == "RedHat" or ansible_os_family == "Debian"

- name: Install programs
  package:
    name: "{{ item }}"
  with_items:
    - atom
    - firefox
    - flash-plugin
    - lastpass-cli
    - messengerfordesktop
    - steam
    - thunderbird
    - yakyak
  become: true
