---
- name: Setup Messenger For Desktop repo
  get_url:
    url: https://bintray.com/aluxian/rpm/rpm
    dest: /etc/yum.repos.d/bintray-aluxian-rpm.repo
  become: true

- name: Install libraries and things
  package:
    name: "{{ item }}"
  with_items:
    - freetype-freeworld
    - gstreamer-ffmpeg
    - gstreamer-plugins-bad
    - gstreamer-plugins-ugly
    - xine-lib-extras-freeworld
  become: true

- name: Install programs
  package:
    name: "{{ item }}"
  with_items:
    - atom
    - firefox
    - messengerfordesktop
    - thunderbird
    - yakyak
  become: true

- name: Fix antialiasing
  gsetting:
    schema: "{{ item.schema }}"
    key: "{{ item.key }}"
    value: "{{ item.value }}"
  with_items:
    - schema: org.gnome.settings-daemon.plugins.xsettings
      key: hinting
      value: "'slight'"
    - schema: org.gnome.settings-daemon.plugins.xsettings
      key: antialiasing
      value: "'rgba'"
