---
- import_tasks: linux.yml
  when: ansible_os_family == "RedHat" or ansible_os_family == "Debian"

- import_tasks: mac.yml
  when: ansible_os_family == "Darwin"

- name: Install programs
  package: name={{ item }}
  with_items:
    - bash-completion
    - lastpass-cli
    - "{{ 'python2-flake8' if ansible_os_family == 'RedHat' else 'flake8' }}"
  become: "{{ package_become }}"

- name: Setup 'opam update' cron job
  cron:
    name: Update opam package list
    job: opam update
    special_time: daily

- name: Create global ~/.gitignore
  copy:
    src: files/gitignore
    dest: "{{ '~/.gitignore' | expanduser }}"

- name: Git configuration
  git_config:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    scope: global
  with_items:
    - name: user.name
      value: Brendan Long
    - name: user.email
      value: self@brendanlong.com
    - name: core.excludesfile
      value: "{{ '~/.gitignore' | expanduser }}"

- name: Setup bashrc
  blockinfile:
    path: ~/.bashrc
    block: "{{ lookup('file', 'files/bashrc') }}"
    create: yes
    marker: "#{mark} Ansible local block"

- name: Install Visual Studio Code extensions
  shell: "code --install-extension {{ item }}"
  with_items:
    - donjayamanne.python
    - freebroccolo.reasonml
    - haaaad.ansible
    - EditorConfig.editorconfig
    - ms-vscode.atom-keybindings
    - ms-vscode.cpptools
    - ms-vscode.csharp
    - sadesyllas.explorer-excluded-files
    - thiagoabreu.vala