---
- include: fedora.yml
  when: ansible_distribution == "Fedora"

- include: linux.yml
  when: ansible_os_family == "RedHat" or ansible_os_family == "Debian"

- name: Install programs
  package:
    name: "{{ item }}"
  with_items:
    - atom
    - firefox
    - flash-plugin
    - lastpass-cli
    - messengerfordesktop
    - python2-flake8
    - steam
    - thunderbird
    - yakyak
  become: true

- name: Install Atom packages
  apm:
    name: "{{ item }}"
  with_items:
    - language-ocaml
    - language-r
    - language-rust
    - language-vala-modern
    - linter-flake8
    - linter-lintr
    - linter-rust
    - ocaml-indent
    - ocaml-merlin
    - rustfmt
