---
- name: Update all packages
  apt:
    upgrade: dist
    update_cache: yes
  become: true

- name: Install Ubuntu-specific packages
  apt: name={{ item }}
  with_items:
    - gdm3
    - gnome-shell
    - opam
    - virtualbox-guest-x11
  become: true

- name: Remove Ubuntu garbage
  apt: name={{ item }} state=absent autoremove=true
  with_items:
    - liboverlay-scrollbar
    #- lightdm
    - overlay-scrollbar
    #- unity
  become: true

- name: Setup 'apt-get update' cron job
  cron:
    name: Update apt-get package list
    job: apt-get update
    special_time: daily
  become: true
