---
- name: Install command-line tools
  package:
    name: "{{ item }}"
  with_items:
    - autoconf
    - automake
    - cmake
    - git
    - libtool
    - nano
    - scons
    - valgrind
  become: true
