---
- include: linux.yml
  when: ansible_os_family == "RedHat" or ansible_os_family == "Debian"

- name: Install command-line tools
  package:
    name: "{{ item }}"
  with_items:
    - autoconf
    - automake
    - cmake
    - direnv
    - git
    - libtool
    - nano
    - scons
  become: "{{ package_become }}"
