---
- include: linux.yml
  when: ansible_os_family == "RedHat" or ansible_os_family == "Debian"

- name: Install command-line tools
  package:
    name: "{{ item }}"
  with_items:
    - autoconf
    - automake
    - cmake
    - direnv
    - git
    - libtool
    - nano
    - scons
  become: "{{ package_become }}"

- name: Setup bashrc
  blockinfile:
    path: ~/.bashrc
    block: "{{ lookup('file', 'files/bashrc') }}"
    create: yes
    marker: "#{mark} Ansible command_line_tools block"

- name: Setup bash_profile
  blockinfile:
    path: ~/.bash_profile
    block: "{{ lookup('file', 'files/bash_profile') }}"
    create: yes
    marker: "#{mark} Ansible command_line_tools block"
