---
- import_tasks: linux.yml
  when: ansible_os_family == "RedHat" or ansible_os_family == "Debian"

- name: Install command-line tools
  package:
    name: "{{ item }}"
  with_items:
    - autoconf
    - automake
    - cmake
    - direnv
    - git
    - libtool
    - nano
    - scons
  become: "{{ package_become }}"

- name: Setup bashrc
  blockinfile:
    path: ~/.bashrc
    block: "{{ lookup('file', 'files/bashrc') }}"
    create: yes
    marker: "#{mark} Ansible command_line_tools block"

- name: Setup bash_profile
  blockinfile:
    path: ~/.bash_profile
    block: "{{ lookup('file', 'files/bash_profile') }}"
    create: yes
    marker: "#{mark} Ansible command_line_tools block"

- name: Create global ~/.gitignore
  copy:
    src: files/gitignore
    dest: "{{ '~/.gitignore' | expanduser }}"

- name: Git configuration
  git_config:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    scope: global
  with_items:
    - name: user.name
      value: Brendan Long
    - name: user.email
      value: self@brendanlong.com
    - name: core.excludesfile
      value: "{{ '~/.gitignore' | expanduser }}"
    - name: branch.autosetuprebase
      value: always