---
- package:
    name: nano
  become: true

- user:
    name: blong
    append: yes
    generate_ssh_key: yes
    groups: wheel
    ssh_key_bits: 2048
  become: true

- known_hosts:
    hash_host: yes
    name: brendanlong.com
    key: "{{ lookup('file', 'files/known_hosts/brendanlong.com') }}"
