---
- import_tasks: fedora.yml
  when: ansible_distribution == "Fedora"

- name: Setup blong user
  user:
    name: blong
    append: yes
    generate_ssh_key: yes
    groups: "{{ 'wheel' if ansible_os_family == 'RedHat' else 'adm' if ansible_os_family == 'Debian' else 'admin' }}"
    ssh_key_bits: 2048
  become: true

- name: Setup known_hosts
  known_hosts:
    name: "{{ item }}"
    key: "{{ lookup('file', 'files/known_hosts/' + item) }}"
  with_items:
    - bitbucket.org
    - brendanlong.com
    - github.com
