---
- name: Install the RPM Fusion repos
  dnf: name={{ item }}
  with_items:
    - http://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_version }}.noarch.rpm
    - http://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_distribution_version }}.noarch.rpm
  when: ansible_distribution == "Fedora"
  become: true

- name: Setup blong user
  user:
    name: blong
    append: yes
    generate_ssh_key: yes
    groups: wheel
    ssh_key_bits: 2048
  become: true

- name: Setup known_hosts
  known_hosts:
    name: "{{ item }}"
    key: "{{ lookup('file', 'files/known_hosts/' + item) }}"
  with_items:
    - bitbucket.org
    - brendanlong.com
    - github.com
